<?php

/**
 * @file
 * Contains password_locker_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function password_locker_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the password_locker_rest module.
    case 'help.page.password_locker_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains custom Rest endpoints for Password Locker.') . '</p>';
      return $output;

    default:
  }
}

/*
 * Implements hook_ENTITY_TYPE_presave().
 */
function password_locker_rest_password_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $name = $entity->get("name")->value;
  $field_email = $entity->get("field_email")->value;
  $field_link = $entity->get("field_link")->uri;
  $field_notes = $entity->get("field_notes")->value;
  $field_password = $entity->get("field_password")->value;
  $field_user_id = $entity->get("field_user_id")->value;
  $entity->set("name", $name . ' This is encrypted data!');
  $entity->set("field_email", $field_email . ' This is encrypted data!');
  $entity->set("field_link", $field_link . ' This is encrypted data!');
  $entity->set("field_notes", $field_notes . ' This is encrypted data!');
  $entity->set("field_password", $field_password . ' This is encrypted data!');
  $entity->set("field_user_id", $field_user_id . ' This is encrypted data!');
}

/**
 * Implements hook_ENTITY_TYPE_load().
 */
function password_locker_rest_password_load($entities) {
  foreach ($entities as $key => $entity) {
    $name = $entities[$key]->get("name")->value;
    $field_email = $entities[$key]->get("field_email")->value;
    $field_link = $entities[$key]->get("field_link")->uri;
    $field_notes = $entities[$key]->get("field_notes")->value;
    $field_password = $entities[$key]->get("field_password")->value;
    $field_user_id = $entities[$key]->get("field_user_id")->value;
    $name = str_replace(" This is encrypted data!", "", $name);
    $field_email = str_replace(" This is encrypted data!", "", $field_email);
    $field_link = str_replace(" This is encrypted data!", "", $field_link);
    $field_notes = str_replace(" This is encrypted data!", "", $field_notes);
    $field_password = str_replace(" This is encrypted data!", "", $field_password);
    $field_user_id = str_replace(" This is encrypted data!", "", $field_user_id);
    $entities[$key]->set("name", $name);
    $entities[$key]->set("field_email", $field_email);
    $entities[$key]->set("field_link", $field_link);
    $entities[$key]->set("field_notes", $field_notes);
    $entities[$key]->set("field_password", $field_password);
    $entities[$key]->set("field_user_id", $field_user_id);
  }
}
