<?php

/**
 * @file
 * Contains password_locker_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function password_locker_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the password_locker_rest module.
    case 'help.page.password_locker_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains custom Rest endpoints for Password Locker.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * @param \Drupal\Core\Entity\EntityInterface $user
 */
function password_locker_rest_user_presave(Drupal\Core\Entity\EntityInterface $user) {
  $user->field_packing_key->value = $user->field_packing_key->value;
}
