<?php

/**
 * @file
 * Contains password_locker_entities.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function password_locker_entities_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the password_locker_entities module.
    case 'help.page.password_locker_entities':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains custom entities for Password Locker.') . '</p>';
      return $output;

    default:
  }
}
